Error handling in REST views
============================

We need to shut up libxml2, so it does not spew errors to stderr:

   >>> import libxml2
   >>> libxml2.registerErrorHandler(lambda ctx, error: None, None)
   1

Now, let's submit a well-formed but invalid XML document:

    >>> print rest("""
    ... POST /groups HTTP/1.1
    ...
    ... <hello>world</hello>
    ... """)
    HTTP/1.1 400 Bad Request
    Content-Length: 39
    Content-Type: text/plain; charset=utf-8
    <BLANKLINE>
    Document not valid according to schema.

An ill-well formed document:

    >>> print rest("""
    ... POST /groups HTTP/1.1
    ...
    ... <what's going on?
    ... """)
    HTTP/1.1 400 Bad Request
    Content-Length: 20
    Content-Type: text/plain; charset=utf-8
    <BLANKLINE>
    Ill-formed document.

Method not supported errors:

    >>> print rest("""
    ... POST / HTTP/1.1
    ...
    ... new user
    ... """)
    HTTP/1.1 405 Method Not Allowed
    Allow: DELETE, GET, OPTIONS, PUT
    Content-Length: ...
    <BLANKLINE>
    Method Not Allowed

    >>> print rest("""
    ... DELETE / HTTP/1.1
    ...
    ... """)
    HTTP/1.1 405 Method Not Allowed
    Allow: DELETE, GET, OPTIONS, PUT
    Content-Length: ...
    <BLANKLINE>
    Method Not Allowed

XXX mg: the two Allow: headers above should only list 'GET', but I have no time
   to make Zope 3 do that right now.


Unauthorized errors are handled by Zope for us:

    >>> print rest("""
    ... POST /groups HTTP/1.1
    ... Content-Type: text/xml
    ...
    ... <object xmlns="http://schooltool.org/ns/model/0.1" title="A Group"/>
    ... """)
    HTTP/1.1 401 Unauthorized
    Content-Length: 0
    WWW-Authenticate: basic realm='Zope'
    <BLANKLINE>


Application errors are also handled with a 400 response.  Let's say a
non valid iCalendar is posted to a user's calendar

    >>> print rest("""
    ... PUT /persons/test HTTP/1.1
    ... Authorization: Basic manager:schooltool
    ... Content-Type: text/xml
    ...
    ... <object xmlns="http://schooltool.org/ns/model/0.1" title="John Doe"/>
    ... """)
    HTTP/1.1 201 Created
    ...

    >>> print rest("""
    ... PUT /persons/test/calendar HTTP/1.1
    ... Authorization: Basic manager:schooltool
    ... Content-Type: text/xml
    ...
    ... !@#$line noise#@$%^
    ... """)
    HTTP/1.1 400 Bad Request
    Content-Length: 80
    Content-Type: text/plain; charset=utf-8
    <BLANKLINE>
    Error parsing iCalendar data: Missing property name in line:
    !@#$line noise#@$%^


Also, there is a special exception that generates a Bad Request
response.  Let's create a view that raises this error:

    >>> from zope.app.testing import ztapi
    >>> from schooltool.app.rest.errors import RestError

    >>> class BadView:
    ...     def __init__(self, context, request):
    ...         self.context = context
    ...         self.request = request
    ...     def POST(self):
    ...         raise RestError("Houston, we've got a problem")

    >>> from schooltool.app.interfaces import ISchoolToolApplication
    >>> from zope.publisher.interfaces.http import IHTTPRequest
    >>> from zope.interface import Interface
    >>> ztapi.provideAdapter((ISchoolToolApplication, IHTTPRequest), Interface,
    ...                      BadView, 'POST')

Now, let's trigger it:

    >>> print rest("""
    ... POST / HTTP/1.1
    ... Content-Type: text/xml
    ... """)
    HTTP/1.1 400 Bad Request
    Content-Length: ...
    Content-Type: text/plain; charset=utf-8
    <BLANKLINE>
    Houston, we've got a problem

And what about NotFound errors?

    >>> print rest("""
    ... POST /hahaha HTTP/1.1
    ... Content-Type: text/xml
    ... """)
    HTTP/1.1 404 Not Found
    Content-Length: 0


Tear down
=========

Restore the libxml2 error handling:

    >>> import sys
    >>> def on_error_callback(ctx, msg):
    ...     sys.stderr.write(msg)
    >>> libxml2.registerErrorHandler(on_error_callback, None)
    1
